### ISSUE TITLE
Block snapping sound when opening code window

### ISSUE THREAD

**Issue by empireboy** [PvB-Groep-1/DevDorp#125]
If you placed 20 blocks and you reopen the code window, the audio for snapping will play 20 times at once, this means that the volume gets louder for more blocks.

There shouldn't be any block sound on opening the code window.

**Comment by waffel183** [comment]
The audio is played in the function SnapTo(). This function gets played when a block snaps to another block. This function apparently also runs when the code window opens, this causes the sounds to happen.
