### ISSUE TITLE
Block programming window covers entire screen

### ISSUE THREAD

**Issue by empireboy** [PvB-Groep-1/DevDorp#32]
Now we have a code window that covers up the entire screen. So when you create something like:
Build Home At 2, 5, you won't see the building location, because the program window covers it.

So what are your thoughts about this?

**Comment by waffel183** [comment]
I think the best solution would be to split the screen in half, 1 half for the game, and the other for the programming.

This will cause issues with the camera dragging, and would have to be modified for this. So I think it is best to do that in another sprint.

**Comment by SharonaVorswijk** [comment]
Maybe we could do something to give the player the option to preview where the building will be built. We could also split the screen but I think I will have make a new popup assets for that.
I suggest the preview option but I don't know if there is enough time for that now. But I think we should save it for the next sprint and take it as feedback now.

**Comment by empireboy** [comment]
Just some heads up on the situation.

The picture below shows what we currently have. We still need more idea's on how to solve this problem.

![image](https://user-images.githubusercontent.com/21023103/81794522-2ff53780-950b-11ea-833e-ec17f13eb39a.png)
_We made the code screen transparent for the playtest, so that the player can see what is happening in the world. This needs to be done differently._

**Comment by empireboy** [comment]
This issue got fixed by adding a grid button to display a grid over the world. We made the code screen fully visible, no transparency. So the player doesn't needs to see the world while using the programming screen.
